services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/tcarwash/runpod_sd_proxy:latest
    ports:
      - "0.0.0.0:9080:9080"
    env_file:
      - .env
    volumes:
      - ./runpod_proxy_data:/data
