name: Docker_Version
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REPOSITORY_TOKEN }}
      - name: Set vars for tag
        id: vars
        shell: bash
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/tcarwash/runpod_sd_proxy:latest
            ghcr.io/tcarwash/runpod_sd_proxy:${{ steps.vars.outputs.VERSION }}
