name: Build_Docker
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: tcarwash
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Set vars for tag
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/tcarwash/runpod_sd_proxy:${{ steps.vars.outputs.sha_short }}
